export type QuoteErrorCode =
  | 'ORGANIZATION_NOT_FOUND'
  | 'MEMBER_REQUIRED'
  | 'VERIFIED_USER_REQUIRED'
  | 'SUBSCRIPTION_REQUIRED'
  | 'BILLING_RECONCILIATION_REQUIRED'
  | 'QUOTE_NOT_FOUND'
  | 'QUOTE_ITEM_NOT_FOUND'
  | 'CUSTOMER_NOT_FOUND'
  | 'CUSTOMER_ARCHIVED'
  | 'CATALOG_SERVICE_NOT_FOUND'
  | 'CATALOG_SERVICE_ARCHIVED'
  | 'QUOTE_NOT_EDITABLE'
  | 'QUOTE_VERSION_CONFLICT'
  | 'INVALID_QUOTE_TRANSITION'
  | 'QUOTE_EXPIRED'
  | 'QUOTE_EMPTY'
  | 'QUOTE_ITEM_LIMIT'
  | 'INVALID_QUOTE_INPUT'
  | 'INVALID_QUOTE_ITEM'
  | 'INVALID_QUOTE_AMOUNT'
  | 'INVALID_QUOTE_DISCOUNT'
  | 'INVALID_QUOTE_VALIDITY'
  | 'QUOTES_BUSY';

export class QuoteError extends Error {
  constructor(readonly code: QuoteErrorCode) {
    super(code);
    this.name = 'QuoteError';
  }
}
