export type WorkOrderErrorCode =
  | 'ORGANIZATION_NOT_FOUND'
  | 'MEMBER_REQUIRED'
  | 'VERIFIED_USER_REQUIRED'
  | 'SUBSCRIPTION_REQUIRED'
  | 'BILLING_RECONCILIATION_REQUIRED'
  | 'QUOTE_NOT_FOUND'
  | 'QUOTE_NOT_APPROVED'
  | 'WORK_ORDER_NOT_FOUND'
  | 'WORK_ORDER_VERSION_CONFLICT'
  | 'WORK_ORDER_NOT_EDITABLE'
  | 'INVALID_WORK_ORDER_TRANSITION'
  | 'INVALID_WORK_ORDER_INPUT'
  | 'INVALID_WORK_ORDER_SCHEDULE'
  | 'ASSIGNEE_REQUIRED'
  | 'ASSIGNEE_NOT_AVAILABLE'
  | 'SERVICE_ADDRESS_REQUIRED'
  | 'CANCELLATION_REASON_REQUIRED'
  | 'WORK_ORDERS_BUSY';

export class WorkOrderError extends Error {
  constructor(readonly code: WorkOrderErrorCode) {
    super(code);
    this.name = 'WorkOrderError';
  }
}
