export type BillingErrorCode =
  | 'ORGANIZATION_NOT_FOUND'
  | 'OWNER_REQUIRED'
  | 'EMAIL_NOT_VERIFIED'
  | 'PLAN_UNAVAILABLE'
  | 'PRICE_MISMATCH'
  | 'SUBSCRIPTION_EXISTS'
  | 'SUBSCRIPTION_NOT_FOUND'
  | 'SUBSCRIPTION_REQUIRED'
  | 'INVALID_SUBSCRIPTION_STATE'
  | 'CHECKOUT_IN_PROGRESS'
  | 'CHECKOUT_EXPIRED'
  | 'BILLING_BUSY'
  | 'BILLING_RECONCILIATION_REQUIRED'
  | 'INVALID_WEBHOOK'
  | 'INVALID_CURSOR'
  | 'MULTIPLE_SUBSCRIPTIONS'
  | 'BILLING_PORTAL_UNAVAILABLE'
  | 'PAYMENT_METHOD_UPDATE_NOT_FOUND'
  | 'INVALID_PAYMENT_METHOD_UPDATE'
  | 'PLAN_CHANGE_NOT_FOUND'
  | 'PLAN_CHANGE_CONFLICT'
  | 'PLAN_CHANGE_SAME_PRICE'
  | 'PLAN_CHANGE_QUOTE_EXPIRED'
  | 'PLAN_CHANGE_UNSUPPORTED'
  | 'PLAN_MEMBER_LIMIT';

export class BillingError extends Error {
  constructor(readonly code: BillingErrorCode) {
    super(code);
    this.name = 'BillingError';
  }
}
