export type ReceivableErrorCode =
  | 'ORGANIZATION_NOT_FOUND'
  | 'MEMBER_REQUIRED'
  | 'VERIFIED_USER_REQUIRED'
  | 'SUBSCRIPTION_REQUIRED'
  | 'BILLING_RECONCILIATION_REQUIRED'
  | 'RECEIVABLES_BUSY'
  | 'WORK_ORDER_NOT_FOUND'
  | 'WORK_ORDER_CANCELED'
  | 'RECEIVABLE_NOT_FOUND'
  | 'RECEIVABLE_VERSION_CONFLICT'
  | 'RECEIVABLE_NOT_EDITABLE'
  | 'RECEIVABLE_HAS_PAYMENTS'
  | 'INVALID_RECEIVABLE_INPUT'
  | 'INVALID_RECEIVABLE_AMOUNT'
  | 'INVALID_RECEIVABLE_DATE'
  | 'INVALID_RECEIVABLE_BALANCE'
  | 'PAYMENT_NOT_FOUND'
  | 'PAYMENT_EXCEEDS_BALANCE'
  | 'PAYMENT_ALREADY_REVERSED'
  | 'INVALID_PAYMENT_METHOD'
  | 'INVALID_PAYMENT_DATE'
  | 'IDEMPOTENCY_CONFLICT'
  | 'REASON_REQUIRED';

export class ReceivableError extends Error {
  constructor(readonly code: ReceivableErrorCode) {
    super(code);
    this.name = ReceivableError.name;
  }
}
